// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Cargo
    {
        public Cargo()
        {
            Funcionarios = new HashSet<Funcionario>();
        }

        public decimal CarId { get; set; }
        public string CarNombre { get; set; }
        public string CarDescripcion { get; set; }
        /// <summary>
        /// Cargos que estan definidos en el Decreto 128-2005
        /// </summary>
        public bool? CarHomologado { get; set; }
        /// <summary>
        /// Usuario que agrega el cargo
        /// </summary>
        public string CarUsuarioAud { get; set; }
        public DateTime? CarFechaAud { get; set; }

        public virtual ICollection<Funcionario> Funcionarios { get; set; }
    }
}