// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class DepartamentoProyecto
    {
        public DepartamentoProyecto()
        {
            Funcionarios = new HashSet<Funcionario>();
        }

        public int KeyDepartamentoProyecto { get; set; }
        public decimal DirId { get; set; }
        public string Nombre { get; set; }
        public string DptCentroCosto { get; set; }
        public string Observacion { get; set; }
        public string CreatedUser { get; set; }
        public DateTime? CreatedDate { get; set; }

        public virtual ICollection<Funcionario> Funcionarios { get; set; }
    }
}