// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Detallepreguntum
    {
        /// <summary>
        /// Key DetallePregunta
        /// </summary>
        public int KeyDtpreg { get; set; }
        /// <summary>
        /// Fk tabla pregunta
        /// </summary>
        public int? FkPreguntaId { get; set; }
        /// <summary>
        /// Fk tabla detalle evaluacion
        /// </summary>
        public int? Fkdtevalua { get; set; }
        /// <summary>
        /// puntaje por cada pregunta del 1 al 4
        /// </summary>
        public int? Puntpregunta { get; set; }

        public virtual Preguntum FkPregunta { get; set; }
        public virtual Evaluaciodetalle FkdtevaluaNavigation { get; set; }
    }
}