// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Direccione
    {
        public Direccione()
        {
            Funcionarios = new HashSet<Funcionario>();
        }

        public decimal DirId { get; set; }
        public string DirNombre { get; set; }
        public string DirDescripcion { get; set; }
        public string DirCentroCosto { get; set; }
        public string DirUsuarioAud { get; set; }
        public DateTime? DirFechaAud { get; set; }
        public bool? DirActivo { get; set; }

        public virtual ICollection<Funcionario> Funcionarios { get; set; }
    }
}