// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Evaluacion
    {
        public Evaluacion()
        {
            Evaluaciodetalles = new HashSet<Evaluaciodetalle>();
        }

        /// <summary>
        /// clave primaria tabla evaluacion Header
        /// </summary>
        public int KeyEval { get; set; }
        /// <summary>
        /// periodo inicial fecha
        /// </summary>
        public DateTime? Periodoinicial { get; set; }
        /// <summary>
        /// periodo final fecha
        /// </summary>
        public DateTime? Periodofinal { get; set; }
        /// <summary>
        /// fecha de evaluacion
        /// </summary>
        public DateTime? Fecha { get; set; }
        /// <summary>
        /// usuario del sistema 
        /// </summary>
        public string Usuario { get; set; }
        /// <summary>
        /// Estado periodo para poder seleccionarlo en formulario crear evaluacion
        /// </summary>
        public bool? Estado { get; set; }

        public virtual ICollection<Evaluaciodetalle> Evaluaciodetalles { get; set; }
    }
}