// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Funcionario
    {
        public Funcionario()
        {
            Evaluaciodetalles = new HashSet<Evaluaciodetalle>();
        }

        public decimal FunId { get; set; }
        public string FunNombre { get; set; }
        public string FunApellidos { get; set; }
        public decimal? CarId { get; set; }
        public decimal? DirId { get; set; }
        public DateTime? FunFnac { get; set; }
        public DateTime? FunIngreso { get; set; }
        public string FunDireccion { get; set; }
        public DateTime? FunFechaIngreso { get; set; }
        public bool? FunActivo { get; set; }
        public string FunCedula { get; set; }
        public decimal SexoId { get; set; }
        public decimal? JefeId { get; set; }
        public decimal? FunCodigo { get; set; }
        public int? DepId { get; set; }
        public int? KeyDepartamentoProyecto { get; set; }
        public int? KeySeccion { get; set; }
        public int? KeyUbicacion { get; set; }

        public virtual Cargo Car { get; set; }
        public virtual DepartamentoProyecto Dep { get; set; }
        public virtual Direccione Dir { get; set; }
        public virtual ICollection<Evaluaciodetalle> Evaluaciodetalles { get; set; }
    }
}