// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Movimiento
    {
        public int? MovId { get; set; }
        public int? FunId { get; set; }
        public int? DirIdNew { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public int? DirIdOld { get; set; }
    }
}