// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Ponderacion
    {
        public Ponderacion()
        {
            Pregunta = new HashSet<Preguntum>();
        }

        /// <summary>
        /// clave primaria
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// detalle de agrupacion de pregunta
        /// </summary>
        public string Descripcion { get; set; }
        /// <summary>
        /// valor de ponderacion
        /// </summary>
        public int? Valor { get; set; }
        /// <summary>
        /// estado para eliminacion logica
        /// </summary>
        public bool? Activo { get; set; }

        public virtual ICollection<Preguntum> Pregunta { get; set; }
    }
}