// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Preguntum
    {
        public Preguntum()
        {
            Detallepregunta = new HashSet<Detallepreguntum>();
        }

        /// <summary>
        /// Key pregunta
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Fk table ponderacion contiene bloques de preguntas
        /// </summary>
        public int? FkPndId { get; set; }
        /// <summary>
        /// detalle de pregunta
        /// </summary>
        public string Descripcion { get; set; }
        /// <summary>
        /// estado de pregunta
        /// </summary>
        public bool? Activo { get; set; }
        public int? IdTpEval { get; set; }

        public virtual Ponderacion FkPnd { get; set; }
        public virtual ICollection<Detallepreguntum> Detallepregunta { get; set; }
    }
}