// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiEvaluacion
{
    public partial class sp_ListadoPreguntasResult
    {
        public int Keypond { get; set; }
        public string ponderacion { get; set; }
        public int? Valor { get; set; }
        public int IDpreg { get; set; }
        public string Pregunta { get; set; }
    }
}
