// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class Tpevaluacion
    {
        public Tpevaluacion()
        {
            Evaluaciodetalles = new HashSet<Evaluaciodetalle>();
        }

        /// <summary>
        /// clave primaria
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Detalle de evaluacion
        /// </summary>
        public string Descripcion { get; set; }

        public virtual ICollection<Evaluaciodetalle> Evaluaciodetalles { get; set; }
    }
}