// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiEvaluacion
{
    public partial class VwListQuestion
    {
        public int Keypond { get; set; }
        public string Ponderacion { get; set; }
        public int? Valor { get; set; }
        public int Idpreg { get; set; }
        public string Pregunta { get; set; }
    }
}